### ISSUE TITLE
Verify that `frostr2::set_frost_client(scope = "user")` has the correct behaviour 

### ISSUE THREAD

**Issue by Aeilert** [Riksrevisjonen/frostr2#1]
Users have reported that the function deletes existing information in their user specific `.Renviron`.

**Comment by ohjakobsen** [comment]
Replace `writeLine` with `write(..., append = TRUE)` on [line 136](https://github.com/Riksrevisjonen/frostr2/blob/e4781a58486ec2bd57ebc650445459eb93912208/R/auth.R#L136)
